#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt remove joe ed nano

sudo apt install i3 stow compton vim screen shellcheck parallel tree gawk jq libxml2-utils htop vim-gnome id-utils exfat-fuse exfat-utils uniutils gettext xmlstarlet curl coreutils silversearcher-ag cifs-utils dos2unix smbclient nfs-common rsync

sudo apt auto-remove
